import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { ThemeProvider } from "../contexts/ThemeContext";
import { AuthProvider } from "../contexts/authContext";
import "./globals.css";
import ReduxProvider from "@/components/common/reduxProvider";
import ProtectedRoute from "@/components/common/ProtctRouter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`transition-colors ${geistSans.variable} ${geistMono.variable}`}
      >
        <ReduxProvider>
          <ProtectedRoute>
            <ThemeProvider>
              <AuthProvider>
                <Header />
                <main className="min-h-[calc(100vh-128px)] px-4 py-8 max-w-6xl mx-auto">
                  {children}
                </main>
                <Footer />
              </AuthProvider>
            </ThemeProvider>
          </ProtectedRoute>         
        </ReduxProvider>
      </body>
    </html>
  );
}
